import type { Metadata } from "next";
import "./globals.css";
import GNB from "@/components/GNB";
import localFont from "next/font/local";

const nanumSquare = localFont({
  src: [
    {
      path: "../../public/fonts/NanumSquareB.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/NanumSquareB.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${nanumSquare.className} antialiased flex flex-col h-screen`}
      >
        <GNB />
        <div className="flex justify-center grow">
          <div className="flex flex-col gap-10 xl:max-w-[1280px] w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
